#  Docker file for Ubuntu 16.04 w/ python 3.6
#  https://gist.github.com/monkut/c4c07059444fd06f3f8661e13ccac619
FROM ubuntu:16.04

#  Create app directory
RUN mkdir /app/

#  Copy package requirements
COPY requirements.txt /app/

RUN apt-get update

#  Install Python 3.6 build for Ubuntu 16.04
RUN apt-get install -y software-properties-common vim
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
RUN apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv
RUN apt-get install -y git
RUN apt-get install -y iputils-ping

#  Update python3-pip
RUN python3.6 -m pip install pip --upgrade
RUN python3.6 -m pip install wheel

#  Install python packages specified in requirements.txt
RUN pip3.6 install --trusted-host pypi.python.org -r /app/requirements.txt

#  Link python path to python3.6
RUN cd /usr/local/bin && \
    ln -s /usr/bin/python3.6 python

CMD [ "python", "/usr/local/bin/gunicorn", "app:app", "-b 0.0.0.0:5000" ]




